import crypto from "crypto";
import jwt from "jsonwebtoken";
import "dotenv/config";

// we will here generate  access token first access token is like band which we get int the waterpark after paying the amount
// and we can go to the rides in the waterpark with the help of this band
// and after 5 pm we have to give this band back
// same as we will generate access token and we can use it for 15 minutes and after 15 minutes we have to give it back
// and we will generate refresh token and we can use it for 7 days and after 7 days we have to give it back
// refresh token is like a key to your room in a hotel it is valid for 7 days and after 7 days you have to give it back 
// and we have to save refresh token in our database to validate it and if user want to logout he can give it back

export const generateAccessToken=(userID)=>{
    return jwt.sign(
        {id: userID},
        process.env.ACCESS_TOKEN_SECRET,
        {expiresIn: process.env.ACCESS_TOKEN_EXPIRES_IN}
    )
};

// this is refresh token which we will use to generate new access token
// and we have to save this refresh token in our database to validate it
// but we will first hash the refresh token and then save it in the database
// why we hash the refresh token?
// 1. security
// 3. if the database is leaked we can still use the refresh token to generate new access token

export const generateRefreshToken=(userID)=>{
    return crypto.randomBytes(32).toString("hex");
}

// here we have hased the refresh token which is generated by crypto.randomBytes(32).toString("hex");
 export const hashRefreshToken=(refreshToken)=>{
    return crypto.createHash("sha256").update(refreshToken).digest("hex");
};  

 // here we just generated the expiry time of the refresh token
export const getRefreshTokenExpiryTime=()=>{
    const expiresAt = new Date();

  expiresAt.setDate(
    expiresAt.getDate() + REFRESH_TOKEN_EXPIRES_DAYS
  );

  return expiresAt;
}
